;; Generated by citrix-workspace-fetch-info.sh on 2026-02-10
;; TODO: Fix. It does not work
(define-module (entelequia packages citrix-workspace)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system gnu)
  #:use-module (guix build syscalls)
  #:use-module (guix gexp)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages libcanberra)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages elf)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages libcanberra)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages web)
  #:use-module (gnu packages xorg)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages audio)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages video)      ; for libva
  #:use-module (gnu packages xdisorg))   ; for libxkbcommon

(define-public citrix-workspace
  (package
    (name "citrix-workspace")
    (version "25.08.10.111")
    (source
     (origin
       (method url-fetch)
       (uri "https://downloads.citrix.com/25724/icaclient_25.08.10.111_amd64.deb?__gda__=exp=1770736849~acl=/*~hmac=0efcdd1d51d79d4d6b0cb41ccc0479c04341594735bb86ac956b505523498b2d")
       ;; Specify file-name to avoid invalid characters from URL in store path
       (file-name (string-append name "-" version ".deb"))
       (sha256
        (base32
         "0xr8lr2x8fx2fg9d38h4vizzaz2fz9ip9xxq80kdhpdpymagqvg1"))))
    (build-system gnu-build-system)
    (arguments
     (list
      #:modules '((guix build gnu-build-system)
                  (guix build utils)
                  (ice-9 match)
                  (ice-9 ftw))  ; For scandir
      #:phases
      #~(modify-phases %standard-phases
          (delete 'configure)
          (delete 'check)
          (delete 'build)
          (replace 'unpack
            (lambda* (#:key source #:allow-other-keys)
              (invoke #$(file-append binutils "/bin/ar") "x" source)
              (invoke #$(file-append tar "/bin/tar") "xf" "data.tar.xz")))
          (replace 'install
            (lambda* (#:key outputs #:allow-other-keys)
              (let* ((out (assoc-ref outputs "out"))
                     (opt (string-append out "/opt"))
                     (bin (string-append out "/bin"))
                     (share (string-append out "/share"))
                     (citrix-dir (string-append opt "/Citrix/ICAClient")))

                ;; Create destination directory
                (mkdir-p opt)

                ;; Copy Citrix files from extracted .deb
                (copy-recursively "opt/Citrix" (string-append opt "/Citrix"))

                ;; Build minimal path-redirect wrapper for Citrix hardcoded paths
                (format #t "Building path-redirect wrapper...~%")
                (let ((wrapper-src (string-append citrix-dir "/path-redirect.c"))
                      (wrapper-so (string-append citrix-dir "/lib/path-redirect.so")))
                  (with-output-to-file wrapper-src
                    (lambda ()
                      (display "#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <fcntl.h>
#include <stdarg.h>

static void *(*real_dlopen)(const char *, int) = NULL;
static FILE *(*real_fopen)(const char *, const char *) = NULL;
static FILE *(*real_fopen64)(const char *, const char *) = NULL;
static int (*real_open)(const char *, int, ...) = NULL;
static int (*real_open64)(const char *, int, ...) = NULL;
static int (*real_access)(const char *, int) = NULL;

static void init(void) {
    if (!real_dlopen) real_dlopen = dlsym(RTLD_NEXT, \"dlopen\");
    if (!real_fopen) real_fopen = dlsym(RTLD_NEXT, \"fopen\");
    if (!real_fopen64) real_fopen64 = dlsym(RTLD_NEXT, \"fopen64\");
    if (!real_open) real_open = dlsym(RTLD_NEXT, \"open\");
    if (!real_open64) real_open64 = dlsym(RTLD_NEXT, \"open64\");
    if (!real_access) real_access = dlsym(RTLD_NEXT, \"access\");
}

static int should_redirect(const char *path) {
    return path && path[0] == '/' && (
        strncmp(path, \"/lib/\", 5) == 0 ||
        strncmp(path, \"/gtk/\", 5) == 0 ||
        strncmp(path, \"/config/\", 8) == 0 ||
        (path[1] >= 'A' && path[1] <= 'Z'));
}

void *dlopen(const char *path, int flag) {
    init();
    if (should_redirect(path)) {
        char newpath[4096];
        snprintf(newpath, sizeof(newpath), \"/opt/Citrix/ICAClient%s\", path);
        return real_dlopen(newpath, flag);
    }
    return real_dlopen(path, flag);
}

FILE *fopen(const char *path, const char *mode) {
    init();
    if (should_redirect(path)) {
        char newpath[4096];
        snprintf(newpath, sizeof(newpath), \"/opt/Citrix/ICAClient%s\", path);
        return real_fopen(newpath, mode);
    }
    return real_fopen(path, mode);
}

FILE *fopen64(const char *path, const char *mode) {
    init();
    if (should_redirect(path)) {
        char newpath[4096];
        snprintf(newpath, sizeof(newpath), \"/opt/Citrix/ICAClient%s\", path);
        return real_fopen64(newpath, mode);
    }
    return real_fopen64(path, mode);
}

int open(const char *path, int flags, ...) {
    init();
    mode_t mode = 0;
    if (flags & O_CREAT) {
        va_list args;
        va_start(args, flags);
        mode = va_arg(args, mode_t);
        va_end(args);
    }
    if (should_redirect(path)) {
        char newpath[4096];
        snprintf(newpath, sizeof(newpath), \"/opt/Citrix/ICAClient%s\", path);
        return real_open(newpath, flags, mode);
    }
    return real_open(path, flags, mode);
}

int open64(const char *path, int flags, ...) {
    init();
    mode_t mode = 0;
    if (flags & O_CREAT) {
        va_list args;
        va_start(args, flags);
        mode = va_arg(args, mode_t);
        va_end(args);
    }
    if (should_redirect(path)) {
        char newpath[4096];
        snprintf(newpath, sizeof(newpath), \"/opt/Citrix/ICAClient%s\", path);
        return real_open64(newpath, flags, mode);
    }
    return real_open64(path, flags, mode);
}

int access(const char *path, int mode) {
    init();
    if (should_redirect(path)) {
        char newpath[4096];
        snprintf(newpath, sizeof(newpath), \"/opt/Citrix/ICAClient%s\", path);
        return real_access(newpath, mode);
    }
    return real_access(path, mode);
}\n")))
                  (invoke #$(file-append gcc "/bin/gcc")
                          "-shared" "-fPIC" "-o" wrapper-so wrapper-src "-ldl"))

                (mkdir-p bin)
                (with-output-to-file (string-append bin "/wfica")
                  (lambda ()
                    (format #t "#!~a/bin/bash~%"
                            #$(file-append bash-minimal "/"))
                    (format #t "# Citrix Workspace wrapper using FHS container~%")
                    (format #t "exec guix shell --container --emulate-fhs \\~%")
                    (format #t "  --preserve='^DISPLAY$' --preserve='^XAUTHORITY$' \\~%")
                    (format #t "  --preserve='^DBUS_' --preserve='^XDG_' \\~%")
                    (format #t "  --share=$HOME --share=/tmp/.X11-unix \\~%")
                    (format #t "  --expose=~a=/opt/Citrix/ICAClient \\~%" citrix-dir)
                    (format #t "  coreutils bash glibc gcc-toolchain openssl openssl@1.1 \\~%")
                    (format #t "  gtk+ cairo gdk-pixbuf pango at-spi2-core glib \\~%")
                    (format #t "  libx11 libxext libxrender libxinerama libxrandr libxfixes \\~%")
                    (format #t "  nss alsa-lib libsecret libcanberra curl \\~%")
                    (format #t "  util-linux:lib libxkbcommon libva pulseaudio \\~%")
                    (format #t "  -- bash -c 'ICAROOT=/opt/Citrix/ICAClient LD_LIBRARY_PATH=/opt/Citrix/ICAClient/lib:/lib:/usr/lib LD_PRELOAD=/opt/Citrix/ICAClient/lib/path-redirect.so exec /opt/Citrix/ICAClient/wfica \"$@\"' bash \"$@\"~%")))
                (chmod (string-append bin "/wfica") #o755)

                (with-output-to-file (string-append bin "/selfservice")
                  (lambda ()
                    (format #t "#!~a/bin/bash~%"
                            #$(file-append bash-minimal "/"))
                    (format #t "# Citrix Workspace storebrowse wrapper using FHS container~%")
                    (format #t "exec guix shell --container --emulate-fhs \\~%")
                    (format #t "  --preserve='^DISPLAY$' --preserve='^XAUTHORITY$' \\~%")
                    (format #t "  --preserve='^DBUS_' --preserve='^XDG_' \\~%")
                    (format #t "  --share=$HOME --share=/tmp/.X11-unix \\~%")
                    (format #t "  --expose=~a=/opt/Citrix/ICAClient \\~%" citrix-dir)
                    (format #t "  coreutils bash glibc gcc-toolchain openssl openssl@1.1 \\~%")
                    (format #t "  gtk+ cairo gdk-pixbuf pango at-spi2-core glib \\~%")
                    (format #t "  libx11 libxext libxrender libxinerama libxrandr libxfixes \\~%")
                    (format #t "  nss alsa-lib libsecret libcanberra curl \\~%")
                    (format #t "  util-linux:lib libxkbcommon libva pulseaudio \\~%")
                    (format #t "  -- bash -c 'ICAROOT=/opt/Citrix/ICAClient LD_LIBRARY_PATH=/opt/Citrix/ICAClient/lib:/lib:/usr/lib LD_PRELOAD=/opt/Citrix/ICAClient/lib/path-redirect.so exec /opt/Citrix/ICAClient/util/storebrowse \"$@\"' bash \"$@\"~%")))
                (chmod (string-append bin "/selfservice") #o755)

                ;; Minimal ELF patching - just set interpreter for executables
                ;; FHS container will provide library paths
                (define (patch-elf-file file)
                  (when (and (file-exists? file)
                             (not (symbolic-link? file))
                             (not (file-is-directory? file)))
                    (catch #t
                      (lambda ()
                        (invoke #$(file-append patchelf "/bin/patchelf")
                                "--set-interpreter"
                                #$(file-append glibc "/lib/ld-linux-x86-64.so.2")
                                file))
                      (lambda (key . args)
                        ;; Silently skip non-ELF files and shared libraries
                        #f))))

                (define (patch-directory dir)
                  (for-each
                   (lambda (entry)
                     (let ((path (string-append dir "/" entry)))
                       (when (and (file-exists? path)
                                  (not (member entry '("." ".."))))
                         (if (file-is-directory? path)
                             (patch-directory path)
                             (patch-elf-file path)))))
                   (or (scandir dir) '())))

                (format #t "Patching ELF binaries (setting interpreter)...~%")
                (patch-directory citrix-dir)

                (when (file-exists? "usr/share")
                  (copy-recursively "usr/share" share))

                (let ((apps-dir (string-append share "/applications")))
                  (mkdir-p apps-dir)
                  (with-output-to-file (string-append apps-dir "/wfica.desktop")
                    (lambda ()
                      (format #t "[Desktop Entry]~%")
                      (format #t "Version=1.0~%")
                      (format #t "Type=Application~%")
                      (format #t "Name=Citrix Workspace~%")
                      (format #t "Comment=Citrix Workspace Client~%")
                      (format #t "Exec=~a/bin/wfica %%f~%" out)
                      (format #t "Icon=~a/share/icons/hicolor/48x48/apps/wfica.png~%" out)
                      (format #t "Terminal=false~%")
                      (format #t "Categories=Network;RemoteAccess;~%")
                      (format #t "MimeType=application/x-ica;~%"))))

                (let ((ica-dir (string-append citrix-dir "/.ICAClient")))
                  (mkdir-p ica-dir)
                  (close-port (open-output-file
                               (string-append ica-dir "/.eula_accepted"))))
                #t))))))
    (native-inputs
     (list tar gzip binutils patchelf gcc))
    (inputs
     (list bash-minimal glibc))
    (propagated-inputs
     ;; These will be available in the FHS container via guix shell
     (list coreutils bash))
    (home-page "https://www.citrix.com/downloads/workspace-app/linux/")
    (synopsis "Citrix Workspace App for remote desktop access")
    (description
     "Citrix Workspace App (formerly Citrix Receiver) is a proprietary client
for accessing remote desktops and applications through Citrix Virtual Apps and
Desktops.  It provides secure access to corporate resources from any device.

This package installs the official Citrix ICA Client for Linux, including
support for HDX protocol, audio redirection, USB redirection, multiple monitors,
and seamless windows.

Note: This is proprietary software distributed under Citrix's terms of service.")
    (license ((@@ (guix licenses) license)
              "Citrix Proprietary"
              "https://www.citrix.com/buy/licensing/agreements.html"
              "Proprietary software license from Citrix"))))

;; Return the package for guix build -f
citrix-workspace
