#!/bin/sh

# Restore pywal colors
wal -R

# Source pywal colors
. "${HOME}/.cache/wal/colors.sh"

# Apply bspwm colors
[ -f ~/.cache/wal/colors-bspwm.sh ] && . ~/.cache/wal/colors-bspwm.sh

#
# UTILITY FUNCTIONS
#

C () { bspc config "$@" & }
R () { bspc rule -a "$@" & }
S () { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# bspwm settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

R Gimp floating=on
R mplayer2 floating=on
R Kupfer.py focus=on
R Screenkey manage=off
R zoom state=floating center=on follow=on border=off
R Emacs state=tiled follow=on
R ${TERMINAL^} state=tiled follow=on
R firefox state=tiled follow=on
R Neomutt state=tiled follow=on
R Slicer follow=off
R Thunar state=floating


C border_width 2
C window_gap 12

C split_ratio 0.52
C borderless_monocle true
C gapless_monocle true

termAppRatio=0.75
screenwidth=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $3}')
screenheight=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $4}')
windowwidth=$( echo "${screenwidth} * ${termAppRatio} "| bc)
windowheight=$( echo "${screenheight} * ${termAppRatio}" | bc)
windowx=$( echo "${screenwidth}/2.0 - ${windowwidth}/2.0"| bc)
windowy=$( echo "${screenheight}/2.0 - ${windowheight}/2.0" | bc)

R TermApp state=floating rectangle=${windowwidth%%.*}x${windowheight%%.*}+$windowx+$windowy

# # Launch Polybar
${HOME}/.config/polybar.local/launch.sh

# # Launch bluetooth widget
# blueberry-tray
